### ISSUE TITLE
page_loader.c - Level up during the game will cause all your material to be displayed as "collected"

### ISSUE THREAD

**Issue by Jakubisek** [kerrambit/InterStellar-Pong#42] opened 2023-09-09 19:18 UTC
I'm not sure if this is intentional, but after the level up my screen showed this:
![image](https://github.com/kerrambit/InterStellar-Pong/assets/109464241/1dca79d1-a0b4-4ade-b5e7-14e86ea5fb75)

**Comment by kerrambit** [comment] 2023-09-09 21:28
@Jakubisek Hello, I would like to ask about more detailed steps. However, if the total materials you have collected through the whole gameplay (not just one game), were displayed as "collected" - that is a bug.

I was not able to reproduce it by now. But I am leaving this issue opened until it is resolved.

**Comment by Jakubisek** [comment] 2023-09-10 07:53
I apologize for not providing sufficient details, here is a video with details reproducing the issue:
[YouTube](https://youtu.be/Uij4jSKTxds)
I edited a player to have 3000 copper but the original issue occurred without change to the player files with stone, not copper.

**Comment by kerrambit** [comment] 2023-09-10 08:45
@Jakubisek Thank you for the video. The source of the bug was discovered and it should be fixed now.

**Closed by kerrambit** 2023-09-10 08:45 UTC
Labels: bug
